### ISSUE TITLE
Implement BLOBHASH and BLOBBASEFEE instructions

### ISSUE THREAD

**Issue by HerbertJordan** [Fantom-foundation/Tosca#468]
As part of the Cancun revision, the BLOB instructions BLOBHASH ([EIP-4844](https://eips.ethereum.org/EIPS/eip-4844)) and BLOBBASEFEE ([EIP-7516](https://eips.ethereum.org/EIPS/eip-7516)) have been added.

To support this instruction in Tosca, the following steps are required:
- update geth dependency to a version that covers Cancun (see #394)
- add BLOBHASH and BLOBBASEFEE instruction support to LFVM + unit tests
- add BLOBHASH and BLOBBASEFEE instruction support to the evmzero + unit tests
- add BLOBHASH and BLOBBASEFEE specification to the CT spec

**Comment by facuMH** [comment]
@HerbertJordan please confirm the following, just to make sure I interpreted correctly the 2 new instructions.
- BLOBBASEFEE: simply a pushes on the stack a u256 to be interpreted as the already existing `BlobBaseFee`, analogous to the already existing `BaseFee` in the `BlockContext`.

- BLOBHASH: reads head of the stack as an `index` and check `index < len(tx.blob_versioned_hashes)` , and then push on the stack `tx.blob_versioned_hashes` which could be implemented as an array of hashes (I believe this should also be in the `BlockContext` since here is where we keep most of the transaction context info).

**Comment by simonlechner** [comment]
This issue has been fixed in #532, #531, #528, 527, #523, #504 and #503.
