### ISSUE TITLE
Add comprehensive unit tests for LFVM's Memory

### ISSUE THREAD

**Issue by HerbertJordan** [Fantom-foundation/Tosca#682]
In particular, make sure that

- [ ] in-variants are defined and maintained by methods
- [ ] memory usage is bound
- [ ] expansion costs are correctly computed
- [ ] capacity is managed correctly
- [ ] reading from and writing to the memory is correctly implemented

**Comment by facuMH** [comment]
Memory invariants defined by functions:
- `getExpansionCosts`:
   . Can not calculate cost of more than `0x1FFFFFFFE0`.
   . Charge 3 gas per word of 32 bytes plus `(w^2)/512`.
- `expandMemory`:
   . Charge for memory before expanding it.
   . Always expand in words of 32 bytes (`toValidMemorySize`).
   . Keep tabs on total memory expansion cost (`memory.currentMemoryCost`).
   . Return errors for overflow or out of gas.
- `getSlice`:
  . Always charge for gas before expanding. 
  . Expanding memory does not modify existing data.
  . Size 0 does not provoke memory expansion.
- Since `readWord` and `set` call to `getSlice`, we get the same assurances and error checking. 

Memory usage is bound:
- This is done by max size check in `getExpansionCosts` and `useGas` in `expandMemory`.
- Tested in `TestGetExpansionCosts`, `TestMemory_expandMemory_ErrorCases`, multiple tests checking for error propagation from `readWord` and set.

Expansion costs are correctly computed:
- Done in `getExpansionCosts`.
- Checked by set fail test, read word error cases, `getSlice` error cases and getExpansionCosts test.

Capacity is managed correctly:
- This involves increasing the memory in chunks of 32 bytes (words), not increasing capacity when size is zero regardless of the offset and not increasing capacity if size+offset < current capacity, memory expansion does not overwrite existing data and newly allocated memory is zeroed.
- Handled by `expandMemory`, and `getSlice`.
- Ensured `TestMemory_expandMemory_expandsMemoryOnlyWhenNeeded`, `TestMemory_getSlice_properlyHandlesMemoryExpansionsAndReturnsExpectedMemory`, `TestMemory_getSlice_ExpandsMemoryIn32ByteChunks`, `TestMemory_getSlice_SizeOfZeroIsNotGrowingTheMemory`, `TestMemory_getSlice_MemoryExpansionDoesNotOverwriteExistingMemory`, `TestMemory_getSlice_MemoryExpansionDoesNotOverwriteExistingMemory` and `TestMemory_getSlice_ExpandsWithZeros`.

Reading from and writing to the memory is correctly implemented:
- This is implemented by `getSlice`, which expands memory if needed, and returns a slice (reference) to the desired range of memory, this can be used to read the memory, or in the case of a write, `set` is used, which calls `getSlice`, and the writes into the returned slice.   
- This is tested by `TestMemory_set_IgnoresEmptyData, `TestMemory_set_PreservesMemoryWhenGrowingAndPadsWithZeros`,  `TestMemory_set_UpdatesDataInMemoryAtGivenOffset`, `TestMemory_getSlice_MemoryExpansionDoesNotOverwriteExistingMemory`, `TestMemory_getSlice_properlyHandlesMemoryExpansionsAndReturnsExpectedMemory`,
